[Circling]
bLegacyCircling = false ; whether to use legacy packages for circling behavior (same behavior as original papyrus mod) or use more lightweight non-package system. 
; Using legacy packages REQUIRES the WaitYourTurnRedux.esp to be present and enabled in the load order. 

bPlayerOnly = true ; if this is false, circling applies to ALL NPCs
bIncludeFollowers = false ; allows followers to benefit from the circling system alongside the player
bIncludeRangedMagic = false ; whether ranged/magic NPCs are included in circling
bTransformProtection = true ; stop attackers during werewolf/vamp lord transformation.
bKillmoveProtection = true ; prevents killmoves on actors that are currently being circled.
bProjectileSlowdown = true; slow projectiles when within a set distance of the player.
bDebugDisplay = false ; highlight attacking actors in white (for debugging)
iMaxAttackers = 2
fProjectileSlowdownRadius = 192.0 ; radius around player where projectiles are slowed
fProjectileSlowdownMultiplier = 0.1 ; multiplier applied to projectile speed within the slowdown radius
fMinFollowUpSeconds = 8.0
fMaxFollowUpSeconds = 16.0
fMinDefenseSeconds = 3.0
fMaxDefenseSeconds = 6.0